### ISSUE TITLE
Metrics won't load

### ISSUE THREAD

**Issue by keithknott26** [aalpern/go-metrics-charts#1]
Hello,

I really like the interface you made for the go-metrics app it looks very clean! Nice job!  

I'm having issues getting my metrics to load however, and I wonder if you might be able to help. I have the metrics.DefaultRegistry exposed via expvar and I can see the metrics show up when I access http://localhost:8080/debug/metrics, but they won't load on the chart when I navigate to http://localhost:8080/debug/metrics/charts

I've attached a sample of what the metrics look like (and the format being exported) in case it helps:

``

  | {
-- | --
  | "alert-accept.count": 299,
  | "alert-accept.fifteen-minute": 0.2296593693657663,
  | "alert-accept.five-minute": 0.34584845202467884,
  | "alert-accept.mean": 0.7222508919696344,
  | "alert-accept.one-minute": 0.18927755938355192,
  | "alert-expire.count": 0,
  | "alert-expire.fifteen-minute": 0,
  | "alert-expire.five-minute": 0,
  | "alert-expire.mean": 0,
  | "alert-expire.one-minute": 0,
  | "alert-insert-count": 298,
  | "alert-insert.count": 298,
  | "alert-insert.fifteen-minute": 0.22893624586297176,
  | "alert-insert.five-minute": 0.3449228024354668,
  | "alert-insert.mean": 0.7198353137792379,
  | "alert-insert.one-minute": 0.18923305108190683,
  | "alert-process.count": 318,
  | "alert-process.fifteen-minute": 0.2593346124319076,
  | "alert-process.five-minute": 0.44867207094945855,
  | "alert-process.mean": 0.768146443215012,
  | "alert-process.one-minute": 0.44621223457858694,
  | "alert-push-failed-count": 0,
  | "alert-push-failed.count": 0,
  | "alert-push-failed.fifteen-minute": 0,
  | "alert-push-failed.five-minute": 0,
  | "alert-push-failed.mean": 0,
  | "alert-push-failed.one-minute": 0,
  | "alert-refresh-fail-count": 0,
  | "alert-refresh-fail.count": 0,
  | "alert-refresh-fail.fifteen-minute": 0,
  | "alert-refresh-fail.five-minute": 0,
  | "alert-refresh-fail.mean": 0,
  | "alert-refresh-fail.one-minute": 0,
  | "alert-refresh-latency": 21,
  | "alert-refresh-process.count": 159,
  | "alert-refresh-process.fifteen-minute": 0.13093094200798724,
  | "alert-refresh-process.five-minute": 0.2302950248985018,
  | "alert-refresh-process.mean": 0.38407351217900526,
  | "alert-refresh-process.one-minute": 0.21695380851562193,
  | "alert-refresh-queued.count": 159,
  | "alert-refresh-queued.fifteen-minute": 0.13093094200798724,
  | "alert-refresh-queued.five-minute": 0.2302950248985018,
  | "alert-refresh-queued.mean": 0.3840735191083801,
  | "alert-refresh-queued.one-minute": 0.21695380851562193,
  | "alert-refresh-success.count": 146,
  | "alert-refresh-success.fifteen-minute": 0.11952100908855974,
  | "alert-refresh-success.five-minute": 0.20774386574996975,
  | "alert-refresh-success.mean": 0.3526712865494113,
  | "alert-refresh-success.one-minute": 0.18643053383224786,
  | "alert-result-fail-count": 0,
  | "alert-result-fail.count": 0,
  | "alert-result-fail.fifteen-minute": 0,
  | "alert-result-fail.five-minute": 0,
  | "alert-result-fail.mean": 0,
  | "alert-result-fail.one-minute": 0,
  | "alert-result-retry-count": 0,
  | "alert-result-retry.count": 0,
  | "alert-result-retry.fifteen-minute": 0,
  | "alert-result-retry.five-minute": 0,
  | "alert-result-retry.mean": 0,
  | "alert-result-retry.one-minute": 0,
  | "alert-result-success.count": 1721,
  | "alert-result-success.fifteen-minute": 1.3296256772283601,
  | "alert-result-success.five-minute": 2.0289368348304784,
  | "alert-result-success.mean": 4.157172652041577,
  | "alert-result-success.one-minute": 1.2140686542001387,
  | "alert-terminate.count": 369,
  | "alert-terminate.fifteen-minute": 0.2762519327409354,
  | "alert-terminate.five-minute": 0.3876225430907432,
  | "alert-terminate.mean": 0.8913397496491946,
  | "alert-terminate.one-minute": 0.10880558395270686,
  | "alert-threads-active": 2,
  | "bandwidth.all.BytesRecv": 1488,
  | "bandwidth.all.BytesSent": 1488,
  | "bandwidth.all.PacketsRecv": 1488,
  | "bandwidth.all.PacketsSent": 1488,
  | "capture_system.50-percentile": 1.215578e+07,
  | "capture_system.75-percentile": 1.2725396e+07,
  | "capture_system.95-percentile": 1.35542884e+07,
  | "capture_system.99-percentile": 1.4597261319999997e+07,
  | "capture_system.999-percentile": 1.7798764e+07,
  | "capture_system.count": 415,
  | "capture_system.fifteen-minute": 0.8731808810509135,
  | "capture_system.five-minute": 0.9490089207946973,
  | "capture_system.max": 1.7798764e+07,
  | "capture_system.mean": 1.1985736573493976e+07,
  | "capture_system.mean-rate": 0.9999694222025002,
  | "capture_system.min": 6.305704e+06,
  | "capture_system.one-minute": 0.9997845477489374,
  | "capture_system.std-dev": 1.2632289951643683e+06,
  | "case-load-latency": 87,
  | "cmdline": ["/var/folders/bd/nnwyd2pd0rb7k8gvmzxpv44m0000gn/T/go-build805279856/b001/exe/dashboard","-t","mq","/Users/keithknott/adeptralink.log"],
  | "common-log-latency": 0.718231,
  | "common-log-read-rate.count": 93756,
  | "common-log-read-rate.fifteen-minute": 74.86223951873896,
  | "common-log-read-rate.five-minute": 123.08300689749426,
  | "common-log-read-rate.mean": 225.92613204168592,
  | "common-log-read-rate.one-minute": 95.50204066031658,
  | "common-memory-free": 63.25459317585301,
  | "common-memory-used": 36.48293963254593,
  | "cpu.Idle": 88,
  | "cpu.IoWait": 0,
  | "cpu.Iowait": 0,
  | "cpu.System": 4,
  | "cpu.User": 7,
  | "datafetch-threads-active": 1,
  | "datafetch-threads-queued": 0,
  | "disk._.Free": 125471096832,
  | "disk._.Total": 500068036608,
  | "disk._Volumes_Recovery.Free": 125471096832,
  | "disk._Volumes_Recovery.Total": 500068036608,
  | "disk._dev.Free": 0,
  | "disk._dev.Total": 197632,
  | "disk._home.Free": 0,
  | "disk._home.Total": 0,
  | "disk._net.Free": 0,
  | "disk._net.Total": 0,
  | "disk._private_var_vm.Free": 125471096832,
  | "disk._private_var_vm.Total": 500068036608,
  | "error-count": 0,
  | "event-threads-active": 1,
  | "load.Load1": 42,
  | "load.Load15": 54,
  | "load.Load5": 50,
  | "mem.Available": 7415820288,
  | "mem.Total": 17179869184,
  | "mem.Used": 9764048896,
  | "memstats": {"Alloc":92018784,"TotalAlloc":9002914192,"Sys":214995192,"Lookups":0,"Mallocs":78504179,"Frees":78144779,"HeapAlloc":92018784,"HeapSys":200081408,"HeapIdle":96837632,"HeapInuse":103243776,"HeapReleased":18358272,"HeapObjects":359400,"StackInuse":1245184,"StackSys":1245184,"MSpanInuse":611424,"MSpanSys":1425408,"MCacheInuse":13888,"MCacheSys":16384,"BuckHashSys":1735505,"GCSys":8894464,"OtherSys":1596839,"NextGC":176363808,"LastGC":1558861804270845000,"PauseTotalNs":10019123,"PauseNs":[39087,14878,17853,19582,26730,86351,80624,89537,95720,79733,40835,59626,54862,202435,90205,60410,54431,98359,35278,59125,44380,80765,78267,81061,69018,87607,45842,146414,188390,111220,56805,133087,105754,255913,129254,86013,78531,68502,92850,46166,123069,68576,81916,107598,87490,79896,46455,55617,65959,42823,168979,37688,82931,118830,67833,61686,69311,76362,117497,58062,74559,93214,50581,68141,72718,52883,124360,38960,90502,54869,76210,62293,168149,67257,156827,86924,121543,139112,66767,69614,82639,105626,82696,54099,87192,129469,51635,49438,146090,316096,87215,54161,122241,40543,68499,92816,86732,161424,59602,68408,70063,86743,79700,53324,259967,57028,101165,50890,64706,83045,68905,72488,99505,150114,68629,60669,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[1558861390240667000,1558861390241521000,1558861390242830000,1558861390245186000,1558861390248061000,1558861395278340000,1558861395323598000,1558861398067735000,1558861398605972000,1558861401333577000,1558861401955025000,1558861402872819000,1558861403807045000,1558861405186568000,1558861405954761000,1558861406426105000,1558861407093852000,1558861407567835000,1558861408180404000,1558861408948427000,1558861409890231000,1558861411785577000,1558861412949981000,1558861413635044000,1558861413944428000,1558861414405527000,1558861414897635000,1558861415361678000,1558861416179974000,1558861416665588000,1558861417136726000,1558861417897883000,1558861419894202000,1558861420517241000,1558861421300313000,1558861424231564000,1558861425276895000,1558861425774952000,1558861426246427000,1558861426707060000,1558861427319639000,1558861427892560000,1558861428487566000,1558861432561406000,1558861438283703000,1558861440092416000,1558861440498718000,1558861440545525000,1558861440867510000,1558861441162809000,1558861441608955000,1558861441933632000,1558861442199594000,1558861442386857000,1558861442544263000,1558861442699977000,1558861442859441000,1558861443132340000,1558861443305511000,1558861443472372000,1558861447133394000,1558861447370992000,1558861447588474000,1558861447836025000,1558861449945023000,1558861451930716000,1558861459900929000,1558861460275604000,1558861465057159000,1558861472277731000,1558861475071188000,1558861483269853000,1558861490701203000,1558861496277643000,1558861504679412000,1558861507275038000,1558861517153814000,1558861519444095000,1558861524107012000,1558861533267933000,1558861534699648000,1558861545676438000,1558861546130827000,1558861552272343000,1558861556648969000,1558861567044714000,1558861579265217000,1558861596267542000,1558861606598780000,1558861615266297000,1558861624864867000,1558861632265044000,1558861635743056000,1558861638267773000,1558861647121450000,1558861655590390000,1558861666139849000,1558861675949041000,1558861683272426000,1558861687595052000,1558861694265447000,1558861702129551000,1558861712299987000,1558861714231763000,1558861722310555000,1558861728268823000,1558861741368474000,1558861747754649000,1558861751219942000,1558861757776984000,1558861765121172000,1558861771657551000,1558861781178589000,1558861784675694000,1558861794269055000,1558861804270845000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":116,"NumForcedGC":0,"GCCPUFraction":0.0004997069200282188,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":308338,"Frees":307656},{"Size":16,"Mallocs":52816831,"Frees":52487885},{"Size":32,"Mallocs":7836496,"Frees":7816684},{"Size":48,"Mallocs":819610,"Frees":817776},{"Size":64,"Mallocs":2493388,"Frees":2491394},{"Size":80,"Mallocs":366625,"Frees":365810},{"Size":96,"Mallocs":345853,"Frees":344825},{"Size":112,"Mallocs":8425151,"Frees":8424765},{"Size":128,"Mallocs":1660021,"Frees":1659509},{"Size":144,"Mallocs":323810,"Frees":323459},{"Size":160,"Mallocs":308724,"Frees":308478},{"Size":176,"Mallocs":57264,"Frees":57147},{"Size":192,"Mallocs":21488,"Frees":21457},{"Size":208,"Mallocs":42005,"Frees":41820},{"Size":224,"Mallocs":10760,"Frees":10753},{"Size":240,"Mallocs":8662,"Frees":8585},{"Size":256,"Mallocs":661316,"Frees":661219},{"Size":288,"Mallocs":266713,"Frees":265952},{"Size":320,"Mallocs":200599,"Frees":200591},{"Size":352,"Mallocs":7046,"Frees":7028},{"Size":384,"Mallocs":1555,"Frees":1156},{"Size":416,"Mallocs":7661,"Frees":7636},{"Size":448,"Mallocs":721,"Frees":721},{"Size":480,"Mallocs":2049,"Frees":2033},{"Size":512,"Mallocs":194379,"Frees":194361},{"Size":576,"Mallocs":1623,"Frees":1610},{"Size":640,"Mallocs":197624,"Frees":197615},{"Size":704,"Mallocs":356,"Frees":351},{"Size":768,"Mallocs":628,"Frees":627},{"Size":896,"Mallocs":8123,"Frees":8077},{"Size":1024,"Mallocs":5479,"Frees":5426},{"Size":1152,"Mallocs":925,"Frees":918},{"Size":1280,"Mallocs":196783,"Frees":196780},{"Size":1408,"Mallocs":622,"Frees":616},{"Size":1536,"Mallocs":5633,"Frees":5590},{"Size":1792,"Mallocs":8685,"Frees":8652},{"Size":2048,"Mallocs":3049,"Frees":3044},{"Size":2304,"Mallocs":2243,"Frees":2235},{"Size":2688,"Mallocs":193623,"Frees":193499},{"Size":3072,"Mallocs":1460,"Frees":1404},{"Size":3200,"Mallocs":480,"Frees":479},{"Size":3456,"Mallocs":865,"Frees":859},{"Size":4096,"Mallocs":10660,"Frees":10596},{"Size":4864,"Mallocs":2261,"Frees":2248},{"Size":5376,"Mallocs":176278,"Frees":176274},{"Size":6144,"Mallocs":236,"Frees":228},{"Size":6528,"Mallocs":156,"Frees":156},{"Size":6784,"Mallocs":103,"Frees":102},{"Size":6912,"Mallocs":28,"Frees":28},{"Size":8192,"Mallocs":12635,"Frees":12573},{"Size":9472,"Mallocs":433,"Frees":424},{"Size":9728,"Mallocs":101,"Frees":101},{"Size":10240,"Mallocs":89,"Frees":89},{"Size":10880,"Mallocs":151408,"Frees":151406},{"Size":12288,"Mallocs":167,"Frees":167},{"Size":13568,"Mallocs":59,"Frees":58},{"Size":14336,"Mallocs":30,"Frees":30},{"Size":16384,"Mallocs":580,"Frees":580},{"Size":18432,"Mallocs":17,"Frees":15},{"Size":19072,"Mallocs":2,"Frees":2}]},
  | "mq-dropped-ack-count": 160,
  | "mq-dropped-response-ack.count": 160,
  | "mq-dropped-response-ack.fifteen-minute": 0.13138388422359218,
  | "mq-dropped-response-ack.five-minute": 0.2294379271852893,
  | "mq-dropped-response-ack.mean": 0.3864911369917866,
  | "mq-dropped-response-ack.one-minute": 0.20288083366749152,
  | "mq-no-response-ack-count": 0,
  | "mq-refresh-request.count": 0,
  | "mq-refresh-request.fifteen-minute": 0,
  | "mq-refresh-request.five-minute": 0,
  | "mq-refresh-request.mean": 0,
  | "mq-refresh-request.one-minute": 0,
  | "mq-refresh-response.count": 0,
  | "mq-refresh-response.fifteen-minute": 0,
  | "mq-refresh-response.five-minute": 0,
  | "mq-refresh-response.mean": 0,
  | "mq-refresh-response.one-minute": 0,
  | "mq-request-ack-count": 109,
  | "mq-request-ack.count": 109,
  | "mq-request-ack.fifteen-minute": 0.09248764351704516,
  | "mq-request-ack.five-minute": 0.17196723902468533,
  | "mq-request-ack.mean": 0.2632969748633915,
  | "mq-request-ack.one-minute": 0.18419725563864126,
  | "mq-request-count": 109,
  | "mq-request-latency": 195,
  | "mq-request.count": 109,
  | "mq-request.fifteen-minute": 0.09246991365820886,
  | "mq-request.five-minute": 0.17188311112454357,
  | "mq-request.mean": 0.2632969990668265,
  | "mq-request.one-minute": 0.1841120432881067,
  | "mq-response-ack-count": 577,
  | "mq-response-ack.count": 417,
  | "mq-response-ack.fifteen-minute": 0.3324908366448388,
  | "mq-response-ack.five-minute": 0.5462696572385345,
  | "mq-response-ack.mean": 1.0072925319408026,
  | "mq-response-ack.one-minute": 0.45452785065208434,
  | "mq-response-count": 576,
  | "mq-response-latency": 247,
  | "mq-response.count": 576,
  | "mq-response.fifteen-minute": 0.46268511614365027,
  | "mq-response.five-minute": 0.7728776013248717,
  | "mq-response.mean": 1.391368073976067,
  | "mq-response.one-minute": 0.6558927549372466,
  | "no-response-ack.count": 0,
  | "no-response-ack.fifteen-minute": 0,
  | "no-response-ack.five-minute": 0,
  | "no-response-ack.mean": 0,
  | "no-response-ack.one-minute": 0,
  | "swapmem.Free": 1626079232,
  | "swapmem.Total": 2147483648,
  | "swapmem.Used": 521404416,
  | "warn-count": 0
  | }
  |  

``
Thanks in advance!!
Keith

**Comment by aalpern** [comment]
@keithknott26 Thanks for the report! I'll look into it. It's possible this hasn't kept up with changes in the go-metrics library, or just that I built it for my own use case and it has bugs :)

**Comment by keithknott26** [comment]
@aalpern,

Thanks so much! I thought maybe there were just too many metrics to display? It would be fantastic to have this looked at, I'm trying to dig through the code to see if I can spot the problem but so far I haven't had much luck and I need to brush up on my javascript. 

I'm happy to provide any debugging information I can or perhaps some kind of log file if it would help.
Edit:  I found an error message in the JS console in the function that collects the metrics datapoints, I've attached a screenshot:

![image](https://user-images.githubusercontent.com/16966683/58395212-ebbc0f00-7ffb-11e9-9dcf-25a6580f346f.png)

Thanks again!
Keith

**Comment by aalpern** [comment]
I've figured out the problem, it's a basic data compatibility thing with the current version of go-metrics. I wrote this code for a fork of a much older version, and haven't kept it up to date. I'll have a fix pushed later today.

**Comment by aalpern** [comment]
@keithknott26  Should be fixed with the latest commit -- update your dependency to version 1.1.0 and let me know if you have any other problems!

**Comment by keithknott26** [comment]
@aalpern 

Wow that was fast! Thank you so much I really appreciate you fixing this so quickly, I'm sure others do as well!

Cheers!
Keith
